sudo: false
language: node_js
cache:
  directories:
  - node_modules
node_js:
- 4.3
- stable
before_install:
- npm i -g npm
script:
- npm t
after_success:
- travis-after-all && npm run semantic-release
deploy:
  provider: npm
  email: futuraprime@gmail.com
  api_key:
    secure: mAlCjC2cN9nExMOubsSu5kA7FH3XWd6kYxG8Padw8qw2RL5vOe74EQVWagCL9SEVqK2NHmasBCR40rJRRqNpaX0LA6ARKheFxBiNrShmPev4DWkgA0rZjZ97Q8CBZws52wmnYwv4hNjv8XXAAJwCCOw0eiPed4vHmoclUyx3DLXCbt6RS4wVqhyPZECHxFH2gksrgxiYRcJATcnfAdeFeybSjFPSScllK+PXfQoni9oriDHV1GBEOIjfITMYRRLrCtnWYnmpruFHMXudP9TB+nMd6nNjG0SJDhREVsRuQdNNbiE4bp7Gr5NgJR4RwCCcbJ86W8q5Vfdy2A3ZOvrGcIDcYy5FXmR9NdzjMWS4koNZb8vsAW7/IBTf0+I++nV4nMSaPc2lvxkfLhwvoimoqRSX0VlI3OBLK3jQH5lYfgnVjwR0kBafW31l7LjKJHJNF1JXeickWteZSo/sTFiOw2Vj3Mqt+hS4fuSWxjKyapyOWAuART9jsfp4OcWiV2BRIc5S2UGVtTq/4g7fG81hlJ7iTIulpcPt3Z1t9ub5NSRIJigpJb8rL31dXMFJSltGEzLbN8TENBQEy/qiQGzLmRe6N/mcmvZb8Ec36lRMaTPgwHmo5cnbjNcMwZIbJG5Ib1U28a15/aC7ZgCn7b6+nX4bayZAZnSzSRdziX12rtk=
  on:
    repo: economist-data-team/utility-dti-isnumeric
env:
  global:
    secure: Meedc7+L7R2u85wKQXvcjOoudx6Zkfym/7ZH+FeyBz3HKQmxY28bTqYN8tGemq4F6ubZnaq7tVGkouGD/BwIKevJloyha9DZ/KCfBpar5ToRIZh+I9QSf0FVEWJ+WNTn2Yp+BJA2F+rZN7Qa97eMdHsYNag/hL/c/bMWGeTU25iXPQGiUpB0JoMRjA05rr17kCegfaZBBBRjn7y9bC0Gj8bHkY3LSD8iD7XJpb2drQNCGaipGm5n2KKVmcbRgMOVlxPWIQFEcZvGWgJC3d03R7UTTruydccBUhs6/0Zp52H2UAz22YpZNbGAi/i4jYfTYAMIki0H4TiBlXhrl6t/71L24kCyQaku3RqMiMeun9tjit41UEolC2e4uC2MrwEOqxf6w722TBIIrEZVtRDS9CSYquZRwZf20USHk5JK8g2H1SP0ykDXC3vy1BxQVoORIpKnmcfxochq3AJhjIvadmqQnghzRxHOs5sS9dr+QFjar0vassFlL/LySUbqSvGuAZ/Oa8tGzqRQV+Y2rjJjD11wh22CDg0jh892FaMOchRCEe+lFlKwwkwQYUyBW9RRNSncsuXOKA4nOgiz5OLXbnPfKUBmhWl9GneJvOJi3kNmlV2JMUz8dDSrYTQyODYn6yHpAYl/tmD4DqhpKUKfjFmLh2diCZg7pWCawTV7E4Y=
